# Generated by Django 6.0.8 on 2026-09-03 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NASAPowerReanalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=128)),
                ('date', models.DateField(help_text='Date of this reanalysis record (UTC)')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature_max', models.FloatField(blank=True, help_text='Daily max temperature at 2 m (°C)', null=True)),
                ('temperature_min', models.FloatField(blank=True, help_text='Daily min temperature at 2 m (°C)', null=True)),
                ('temperature_mean', models.FloatField(blank=True, help_text='Daily mean temperature at 2 m (°C)', null=True)),
                ('wind_speed_10m_mean', models.FloatField(blank=True, help_text='Daily mean wind speed at 10 m (m/s)', null=True)),
                ('wind_direction_10m_mean', models.FloatField(blank=True, help_text='Daily mean wind direction at 10 m (degrees, meteorological)', null=True)),
                ('specific_humidity', models.FloatField(blank=True, help_text='Daily mean specific humidity at 2 m (g/kg)', null=True)),
                ('relative_humidity', models.FloatField(blank=True, help_text='Daily mean relative humidity at 2 m (%)', null=True)),
                ('precipitation', models.FloatField(blank=True, help_text='Total daily precipitation (mm/day)', null=True)),
                ('surface_shortwave_radiation', models.FloatField(blank=True, help_text='All-sky surface shortwave downward irradiance (W/m²)', null=True)),
                ('surface_pressure', models.FloatField(blank=True, help_text='Daily mean surface pressure (kPa)', null=True)),
                ('boundary_layer_height', models.FloatField(blank=True, help_text='Daily mean planetary boundary layer height (m)', null=True)),
                ('source', models.CharField(default='nasa_power', max_length=32)),
            ],
            options={
                'verbose_name': 'NASA POWER Reanalysis',
                'verbose_name_plural': 'NASA POWER Reanalysis Records',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'date'], name='weather_nas_latitud_fc9494_idx'), models.Index(fields=['date'], name='weather_nas_date_82fc79_idx'), models.Index(fields=['city', 'date'], name='weather_nas_city_7eddb8_idx')],
                'unique_together': {('latitude', 'longitude', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=128)),
                ('forecast_generated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='UTC time this forecast batch was created')),
                ('valid_time', models.DateTimeField(help_text='UTC hour this forecast row is valid for')),
                ('lead_hours', models.PositiveSmallIntegerField(help_text='Hours ahead from forecast_generated_at (1-72)')),
                ('temperature_2m', models.FloatField(blank=True, help_text='°C', null=True)),
                ('relative_humidity_2m', models.FloatField(blank=True, help_text='%', null=True)),
                ('precipitation', models.FloatField(blank=True, help_text='mm', null=True)),
                ('precipitation_probability', models.FloatField(blank=True, help_text='Precipitation probability (%)', null=True)),
                ('wind_speed_10m', models.FloatField(blank=True, help_text='km/h — key input for AQI dispersion', null=True)),
                ('wind_direction_10m', models.FloatField(blank=True, help_text='Degrees — key input for AQI dispersion', null=True)),
                ('wind_gusts_10m', models.FloatField(blank=True, help_text='km/h', null=True)),
                ('surface_pressure', models.FloatField(blank=True, help_text='hPa', null=True)),
                ('cloud_cover', models.FloatField(blank=True, help_text='%', null=True)),
                ('visibility', models.FloatField(blank=True, help_text='m', null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('boundary_layer_height', models.FloatField(blank=True, help_text='Planetary boundary layer height (m) — affects pollutant mixing', null=True)),
                ('source', models.CharField(default='open_meteo', max_length=32)),
            ],
            options={
                'verbose_name': 'Weather Forecast',
                'verbose_name_plural': 'Weather Forecasts',
                'ordering': ['valid_time'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'valid_time'], name='weather_wea_latitud_4aa0fe_idx'), models.Index(fields=['valid_time'], name='weather_wea_valid_t_70364f_idx'), models.Index(fields=['city', 'valid_time'], name='weather_wea_city_cdbb4d_idx'), models.Index(fields=['forecast_generated_at'], name='weather_wea_forecas_757102_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Decimal degrees, WGS-84')),
                ('longitude', models.FloatField(help_text='Decimal degrees, WGS-84')),
                ('city', models.CharField(blank=True, help_text='Human-readable city / district name (optional)', max_length=128)),
                ('observed_at', models.DateTimeField(help_text='UTC time the observation was valid for (from Open-Meteo)')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, help_text='UTC time this record was written to the DB')),
                ('temperature_2m', models.FloatField(blank=True, help_text='Air temperature at 2 m height (°C)', null=True)),
                ('relative_humidity_2m', models.FloatField(blank=True, help_text='Relative humidity at 2 m (%)', null=True)),
                ('precipitation', models.FloatField(blank=True, help_text='Precipitation in the last hour (mm)', null=True)),
                ('wind_speed_10m', models.FloatField(blank=True, help_text='Wind speed at 10 m height (km/h)', null=True)),
                ('wind_direction_10m', models.FloatField(blank=True, help_text='Wind direction at 10 m, meteorological (°)', null=True)),
                ('wind_gusts_10m', models.FloatField(blank=True, help_text='Wind gusts at 10 m (km/h)', null=True)),
                ('surface_pressure', models.FloatField(blank=True, help_text='Surface air pressure (hPa)', null=True)),
                ('cloud_cover', models.FloatField(blank=True, help_text='Total cloud cover (%)', null=True)),
                ('visibility', models.FloatField(blank=True, help_text='Horizontal visibility (m)', null=True)),
                ('weather_code', models.IntegerField(blank=True, help_text='WMO weather interpretation code', null=True)),
                ('source', models.CharField(default='open_meteo', help_text='Data provider identifier', max_length=32)),
            ],
            options={
                'verbose_name': 'Weather Observation',
                'verbose_name_plural': 'Weather Observations',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'observed_at'], name='weather_wea_latitud_f65fc6_idx'), models.Index(fields=['observed_at'], name='weather_wea_observe_606f9c_idx'), models.Index(fields=['city'], name='weather_wea_city_6c8f7d_idx')],
            },
        ),
    ]
